/* Generated By:JavaCC: Do not edit this line. DslConstants.java */
package egtry.dsl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DslConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 5;
  /** RegularExpression Id. */
  int QUOTE = 6;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int IMAGE = 8;
  /** RegularExpression Id. */
  int SOURCE = 9;
  /** RegularExpression Id. */
  int WITH = 10;
  /** RegularExpression Id. */
  int HEADING = 11;
  /** RegularExpression Id. */
  int PARAGRAPH = 12;
  /** RegularExpression Id. */
  int LINK = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int TEXT = 15;
  /** RegularExpression Id. */
  int COLOR = 16;
  /** RegularExpression Id. */
  int FONT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<ALPHANUMERIC>",
    "\"\\\"\"",
    "\"ADD\"",
    "\"IMAGE\"",
    "\"SOURCE\"",
    "\"WITH\"",
    "\"HEADING\"",
    "\"PARAGRAPH\"",
    "\"LINK\"",
    "\"AND\"",
    "\"TEXT\"",
    "\"COLOR\"",
    "\"FONT\"",
  };

}
